x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '8.2.1'
  publishedVersionMetadata:
    releaseNote: >-
      SYNTASA platform release 8.2.1
    releaseTypes:
      - Feature
    recommended: true
  partnerId: syntasa-public
  solutionId: syntasa-behavioral-sentiment-analytics.endpoints.syntasa-public.cloud.goog
  managedUpdates:
    kalmSupported: true
  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 2
          memory: 16384Mi

  images:
    '':
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
    ubbagent:
      type: string
      default: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
      properties:
        ubbagentImage:
          type: FULL
    haproxy-ingress:
      properties:
        haproxyIngressImage:
          type: FULL
    syntasa-installer-agent:
      properties:
        syntasaInstallerAgentImage:
          type: FULL
    syntasa-management:
      properties:
        syntasaManagementImage:
          type: FULL
    syntasa-management-auth:
      properties:
        syntasaManagementAuthImage:
          type: FULL
    syntasa-management-console:
      properties:
        syntasaManagementConsoleImage:
          type: FULL

form:
  - widget: help
    description: |-
      <h2>Thank you for your interest in SYNTASA</h2>

      <p>For more information about the SYNTASA Google Marketplace Configuration Parameters on the left, please visit the following guide:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace/blob/master/docs/MARKETPLACE_CONFIG_OPTIONS.md#syntasa-google-cloud-marketplace-configuration-options">Syntasa Marketplace Installation and Configuration Documentation</a>

      <p>For more information about the SYNTASA solution please visiting the following github repo:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace#syntasa-customer-intelligence-platform-for-google-marketplace">Syntasa Marketplace Installation and Configuration Documentation</a></p>

      <p>For any additional support please visit: <a href="https://help.syntasa.com">help.syntasa.com</a></p>

properties:
  name: 
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  gcpServiceAccount:
    type: string
    title: IAM Service Account to use when deploying SYNTASA resources
    default: ""
    x-google-marketplace:
      type: STRING
  haproxy.service.loadBalancerHostname:
    type: string
    default: ""
    title: Hostname mapping to use for your load balancer
    x-google-marketplace:
      type: STRING
  haproxy.service.loadBalancerIP:
    type: string
    default: ""
    title: Static ip to use for your load balancer (this must be reserved beforehand, please see docs)
    x-google-marketplace:
      type: STRING
  haproxy.service.loadBalancerSourceRanges:
    type: string
    default: "0.0.0.0/0"
    title: Comma separated list of IP addresses to whitelist in CIDR Notation e.g. 0.0.0.0/0,1.2.3.7/24
    x-google-marketplace:
      type: STRING
  roles.serviceAccount:
    type: string
    title: Syntasa Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          This service account is used to deploy the resources for the syntasa application including
          secrets, configmaps, ingresses, deployments, services, endpoints, nodes, pods, persistentvolumes, and monitor logs.
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: [ "", "apps" ]
                resources: [ "configmaps", "endpoints", "nodes", "pods", "services", "namespaces", "events", "serviceaccounts", "persistentvolumes", "persistentvolumeclaims", "secrets", "pods/log" ]
                verbs: [ "*" ]
              - apiGroups: [ "extensions", "apps", "networking.k8s.io", "coordination.k8s.io" ]
                resources: [ "ingresses", "ingresses/status", "deployments", "ingressclasses", "leases" ]
                verbs: [ "*" ]
              - apiGroups: [ "apiextensions.k8s.io" ]
                resources: [ "customresourcedefinitions" ]
                verbs: [ "*" ]
              - apiGroups: [ "sparkoperator.k8s.io" ]
                resources: [ "*" ]
                verbs: [ "*" ]
              - apiGroups: [ "batch" ]
                resources: [ "*" ]
                verbs: [ "*" ]
              - apiGroups: [ "rbac.authorization.k8s.io" ]
                resources: [ "rolebindings", "roles", "clusterrolebindings", "clusterroles" ]
                verbs: [ "*" ]
              - apiGroups: [ "v1" ]
                resources: [ "serviceaccounts" ]
                verbs: [ "*" ]

  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: TLS_CERTIFICATE_KEY
          base64EncodedCertificate: TLS_CERTIFICATE_CRT
required:
  - name
  - namespace
  - haproxy.service.loadBalancerIP
  - haproxy.service.loadBalancerSourceRanges
